server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users_local
    username: users_local
    password:
    hikari:
      maximum-pool-size: 40
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
